### ISSUE TITLE
Synthesis error

### ISSUE THREAD

**Issue by mohdumar644** [Xilinx/QNN-MO-PYNQ#11]
The provided ./make-hw.sh  fails to fit the implemented design on the PYNQ 7z020.

**Comment by giuliogamba** [comment]
Which version of Vivado HLS are you using? On which platform?

**Comment by mohdumar644** [comment]
2018.2 on Linux.
It does fit using 2017.4 though.

**Comment by giuliogamba** [comment]
Sorry, the HW flow is supported in Vivado version 2017.4
