### ISSUE TITLE
Hardware config vs accuracy

### ISSUE THREAD

**Issue by nqdtan** [Xilinx/QNN-MO-PYNQ#14]
Hello,

Is it possible to change the parameter(s) in config.h file without affecting the inference result? As an example, I tried changing MAX_PE from 64 to 32 to generate a smaller accelerator (so that I could fit other IP blocks on the PYNQ). When I ran the Python test code, the inference could not accurately detect object in a given picture anymore. I thought modifying MAX_PE only affects the resource consumption and performance, yet I expected that the computational result would not change. Does changing configuration (in this case, MAX_PE) require re-training the network?

**Comment by giuliogamba** [comment]
Hi, 

no, you can't change the parallelism without affecting the results. The network parameters (stored in the params folder) are generated in an hardware dependent way. Changing the parallelism does not need retraining but only a re-shuffling of the parameters.
For the moments the scripts generating the parameters in the HW dependent way are not open-sourced though.
