### ISSUE TITLE
C synthesis error

### ISSUE THREAD

**Issue by wangent123** [Xilinx/QNN-MO-PYNQ#16]
hi，
     When i rebuild the HLS project,there are some errors: default template arguments for a function template are a C++11 extension [-Wc++11-extensions] and error: use of undeclared identifier 'constexpr'.
So i need your help. Thank you very much.

**Comment by giuliogamba** [comment]
Which version of Vivado HLS are you using?

**Comment by wangent123** [comment]
> Which version of Vivado HLS are you using?

2017.2

**Comment by giuliogamba** [comment]
The recommended Vivado version to reproduce the HW flow is 2017.4

**Comment by wangent123** [comment]
> The recommended Vivado version to reproduce the HW flow is 2017.4
thank you so much
