### ISSUE TITLE
cannot find -lsds_lib

### ISSUE THREAD

**Issue by lyn2333** [Xilinx/QNN-MO-PYNQ#20]
Hi
I use the pynq z2 with img v2.3.  When I input the ''sudo pip3.6 install git+https://github.com/Xilinx/QNN-MO-PYNQ.git", the error is '/usr/bin/arm-linux-gnueabihf-ld : cannot find -lsds_lib'. Please help me, it troubled me for three days.

**Comment by giuliogamba** [comment]
Just pushed the update supporting PYNQ 2.3, please try now

**Comment by giuliogamba** [comment]
The official support to PYNQ2.3 has just been pushed, please check now if this works for you.

**Comment by lyn2333** [comment]
Thank you very much! You are so great!!!
