### ISSUE TITLE
hw rebuild

### ISSUE THREAD

**Issue by lyn2333** [Xilinx/QNN-MO-PYNQ#21]
My board is PYNQ-Z2. When I implement the project, something wrong happens. How could I deal with it?

The follow is errors:
[Place 30-640] Place Check : This design requires more Slice LUTs cells than are available in the target device. This design requires 62315 of such cell types but only 53200 compatible sites are available in the target device. Please analyze your synthesis results and constraints to ensure the design is mapped to Xilinx primitives as expected. If so, please consider targeting a larger device. Please set tcl parameter "drc.disableLUTOverUtilError" to 1 to change this error to warning.

![default](https://user-images.githubusercontent.com/43510456/48243450-72701c80-e41b-11e8-8856-850cd84e36a7.JPG)

**Comment by giuliogamba** [comment]
Duplicate #11, supported Vivado version is 2017.4

**Comment by lyn2333** [comment]
I have one question: if I rebuilt the project  using vivado 2017.4 and do some modifications, then generate bitsreams, could I use the img v2.3 to call its functions? I find something in "https://pynq.readthedocs.io/en/latest/pynq_sd_card.html#building-the-image" like this:
![66](https://user-images.githubusercontent.com/43510456/48273200-59975380-e47b-11e8-9f79-61843bcf2e50.JPG)

**Comment by giuliogamba** [comment]
Yes, you can

**Comment by lyn2333** [comment]
I am so sorry to disturb you again.
    The utilization ratio of BRAM is too high, which accounts for about 99% . I have no room for revision and I didn't find the IP --- Block Memory Generator. Could you tell me where to decrease it? 
Thank you.

**Comment by lyn2333** [comment]
![gg](https://user-images.githubusercontent.com/43510456/48298975-17b0f080-e501-11e8-80b7-1f1dd0a33a30.JPG)
![lll](https://user-images.githubusercontent.com/43510456/48298976-17b0f080-e501-11e8-923d-30af347913d3.JPG)
