### ISSUE TITLE
Is your network trained with swapped X / Y axis ?? 

### ISSUE THREAD

**Issue by Pe3ucTop** [Xilinx/QNN-MO-PYNQ#22]
Hello, 
Analyzing your provided Python code I came to : 
Image loaded  array axes (shape) (3,h,w) = [Color, Y, X]  , it's ok
then going   img_copy = np.swapaxes(img_copy, 0,2) with result [X,Y,C]  <- Not Ok for most image operations
then in utils.conv_layer transpose(0, 3, 1, 2)  on [1,X,Y,C] with result [1,C,X,Y] <- here it not ok for Darknet too.. 
And then you get elements for convolution like from correctly positioned image ...
After buffer prepare, same data (with incorrect convolution direction is passed to Accelerator) ..

Could you comment on that ?? 

Also I tried loading "dog.jpg" image whith  OpenCV , it give me better result.
But OpenCV have different colour space BGR  (not RGB) , did you use RGB for training ?

**Comment by nickfraser** [comment]
This network was trained in [darknet](https://github.com/pjreddie/darknet). The preprocessing code is the same as darknet, and therefore I suggest you look the their preprocessing techniques.
