### ISSUE TITLE
What's the format of json file of the network structure definition?

### ISSUE THREAD

**Issue by Yuxishan2** [Xilinx/QNN-MO-PYNQ#23]
In the  "QNN-MO-PYNQ/qnn/src/network/sw/main.cpp"
line 66 to 68:
`extern "C" {
    void initParameters(unsigned int const batch, unsigned int const threads);
    void initAccelerator(char const *networkJson, char const *layerJson);`
The json file of network need to be assigned.
But is the format of this json file the same with general deeplearning framework like theano?

**Comment by giuliogamba** [comment]
Hi, the json format used in the runtime to load the neural network structure has been developed ad-hoc for this. You can see examples of the 2 networks [here](https://github.com/Xilinx/QNN-MO-PYNQ/blob/master/qnn/params/tinier-yolo-layers.json) and [here](https://github.com/Xilinx/QNN-MO-PYNQ/blob/master/qnn/params/dorefanet-layers.json). 
Hope this helps
