### ISSUE TITLE
pip3 install problem

### ISSUE THREAD

**Issue by chiayilin1991** [Xilinx/QNN-MO-PYNQ#24]
My board is pynq-z2.
And, I tried to pip3 install git+https://github.com/Xilinx/QNN-MO-PYNQ.git, 
but there was no any response after cloning.

Collecting git+https://github.com/Xilinx/QNN-MO-PYNQ.git
  Cloning https://github.com/Xilinx/QNN-MO-PYNQ.git to /tmp/pip-bl5011_8-build

I had  waited for about 20min.
By the way, I could ping github.com.

**Comment by giuliogamba** [comment]
You can try to first clone the repository on the board, then move to the folder and use the command `pip3 install ./`. The installation process is quite slow, and in the non-verbose mode not many information is given to the user about the status. You can try to execute pip3 with the flag `-v` to increase verbosity and check the installation status.

**Comment by giuliogamba** [comment]
@chiayilin1991 Where you able to solve the problem?
