### ISSUE TITLE
HW rebuild on windows

### ISSUE THREAD

**Issue by Sayf-Khan** [Xilinx/QNN-MO-PYNQ#29]
Hello,

I am trying to use Vivado HLS 2017.4 command prompt on Windows 10 to rebuild the script but when I followed the instructions, it gave the following error when entering the following line "./make-hw.sh W1A2 pynqz1-z2 h" .

C:\Users\Sayf\Desktop\QNN\QNN-MO-PYNQ-master\QNN-MO-PYNQ-master\qnn\src\network>./make-hw.sh W1A2 pynqz1-z2 h
'.' is not recognized as an internal or external command,
operable program or batch file.

Kind regards,
Sayf Khan

**Comment by giuliogamba** [comment]
We do not support Windows hardware rebuild, but you can take inspiration by the scripts (for [Vivado HLS](https://github.com/Xilinx/QNN-MO-PYNQ/blob/master/qnn/src/network/hls-syn.tcl) and [Vivado](https://github.com/Xilinx/QNN-MO-PYNQ/tree/master/qnn/src/library/script/ultra96)) and execute them in your Windows environment.
