### ISSUE TITLE
Using this project to implement binary(qnn) version of tiny yolo2

### ISSUE THREAD

**Issue by Thilanka97** [Xilinx/QNN-MO-PYNQ#30]
Hey,
I am planning to implement QNN version of tiny yolo2. Because I want to implement tiny yolo2 on fpga and I am planning to use bnn for that. Then I got to know about this project. So I would like to have your advice and ideas about changing this to work for tiny yolo2 on pync. 
It would be a great help if you could give me your ideas. 

Thanks in advance !

**Comment by Thilanka97** [comment]
@giuliogamba hey,
First of all is this possible? Can this be changed to work with tiny yolo2 ?

**Comment by giuliogamba** [comment]
You can use the HLS library provided to virtually implement all QNNs. 
Nonetheless, we do not provide support or assistance in that process.
