### ISSUE TITLE
Install without the Internet?

### ISSUE THREAD

**Issue by Lavr18** [Xilinx/QNN-MO-PYNQ#31]
Hi,

I don't have the Internet connection on my PYNQ board, but I can access it locally.
Is there a way to install the framework without the Internet?

Thanks.
Aliaksei

**Comment by ussamazahid96** [comment]
Clone QNN-MO-PYNQ on PC having internet, clone `https://github.com/Tencent/rapidjson` into `QNN-MO-PYNQ/qnn/src/library`, clone `https://github.com/giuliogamba/darknet` into `QNN-MO-PYNQ/`, and copy this complete QNN-MO-PYNQ folder on PYNQ sdcard.

On PYNQ board navigate to `QNN-MO-PYNQ/darknet/` and run `make -j2 all`, edit the setup.py file `QNN-MO-PYNQ/setup.py` and comment the line which invokes the subprocess to make darknet i.e. `    subprocess.check_output(["git", "clone", "https://github.com/giuliogamba/darknet", my_path + "darknet"])` save and then run `sudo python3.6 setup.py install`

Note that the installation path will be `/usr/local/lib/python3.6/dist-packages/qnn_loopback-0.1-py3.6.egg/qnn/` and you have to update the paths in jupyter notebooks accordingly.
