### ISSUE TITLE
Check FPGA hardware utilization of tinyYOLO

### ISSUE THREAD

**Issue by Lavr18** [Xilinx/QNN-MO-PYNQ#33]
Hi,

Your framework is really good! It works great on my PYNQ board. Thanks for your job.

I am now trying to test the hardware utilization of the tiny YOLO QNN used in the examples on my FPGA.
I believe it should be done using Vivado.
Could you please provide a guide on doing this on Windows 10? I use Vivado 2018.3.

Thanks,
Aliaksei

**Comment by giuliogamba** [comment]
Hi, 

the hardware utilization of the overlay is shown in the README available [here](https://github.com/Xilinx/QNN-MO-PYNQ/tree/master/qnn/src/network/W1A3). 
If you want to replicate, the hardware build, we do support this in a UNIX environment by executing the `make-hw.sh` script available [here](https://github.com/Xilinx/QNN-MO-PYNQ/blob/master/qnn/src/network/make-hw.sh). 
We do not support Windows hardware rebuild, but you can take inspiration by the scripts (for [Vivado HLS](https://github.com/Xilinx/QNN-MO-PYNQ/blob/master/qnn/src/network/hls-syn.tcl) and [Vivado](https://github.com/Xilinx/QNN-MO-PYNQ/tree/master/qnn/src/library/script/ultra96)) and execute them in your Windows environment.
