### ISSUE TITLE
how does the function "draw_detection_python" work?

### ISSUE THREAD

**Issue by Icarus0519** [Xilinx/QNN-MO-PYNQ#36]
Hi,

I want to send the coordinates of the identified object to my arduino, so I have to understand how the recognition box is drawn, which is done by the function "draw_detection_python", When I want to understand it through the help command, I cannot learn more about it. so could you please help me?

kind regards,
Icarus.

**Comment by giuliogamba** [comment]
The function is defined within darknet, you can check the definition and implementation [here](https://github.com/giuliogamba/darknet/blob/master/examples/detector.c).
