### ISSUE TITLE
Open HLS project 

### ISSUE THREAD

**Issue by jason911ss** [Xilinx/QNN-MO-PYNQ#39]
Thanks for your work .
I'm trying to open the HLS project of this work by
: vivado_hls -f hls-syn.tcl
but I don't know what exactly I should type for argv defined in the .tcl
such as config_hwsrcdir, config_proj_part, config_clkperiod ...
Could you please give me some guide ? I will be very greatful.
Sorry that I'm a beginer and Vivado or HLS.

**Comment by giuliogamba** [comment]
You should use the `make-hw.sh` script with the `-h` flag to run the Vivado hls synthesis. The project will be generated under `output\hls-syn\W1A2-ultra96\vivado_hls` and you can easily open the project.
