### ISSUE TITLE
lib_sw_W1A3 .so 

### ISSUE THREAD

**Issue by wangent123** [Xilinx/QNN-MO-PYNQ#40]
hi,
   i have a problem about the files of  lib_sw_W1A3.so and lib_sw_W1A3.so. i want to know the  function of these two documents. Thank you！

**Comment by giuliogamba** [comment]
You can find the source code used to compile the library [here](https://github.com/Xilinx/QNN-MO-PYNQ/blob/master/qnn/src/network/sw/main.cpp).
Hope this helps.
