### ISSUE TITLE
Question on the output activation

### ISSUE THREAD

**Issue by toannv123** [Xilinx/QNN-MO-PYNQ#47]
Hello,
 
   I don't understand why for the network W1A3, the output activation is 3-bit wide, the accumulated value (stored in the macRegisters) is compared with 5 (=3*2-1) thresholds read from the threshold memory. Can you explain me this case?

Many thanks!

**Comment by giuliogamba** [comment]
Hi, 

it's actually 2^3-1=7 thresholds. That's the amount of thresholds you need to allow 8 output possible values (represented in 3 bit). 
Hope this clarifies your doubt.

**Comment by toannv123** [comment]
Ok, thank you so much.
