### ISSUE TITLE
Hardware design rebuild support

### ISSUE THREAD

**Issue by kavyakl** [Xilinx/QNN-MO-PYNQ#54]
I am trying to do the hardware design rebuilding and it keeps saying commands of vivado and vivado_hls are not found.
please help.

**Comment by giuliogamba** [comment]
You need to install vivado and vivado hls. Please refer to the installation guide. [This ](https://www.xilinx.com/support/documentation/sw_manuals/xilinx2019_2/ug973-vivado-release-notes-install-license.pdf) guide might help.
