### ISSUE TITLE
Who can tell me how to rebuild hardware design in Windows？thanks.

### ISSUE THREAD

**Issue by gexianwei1231** [Xilinx/QNN-MO-PYNQ#64]
在Windows里怎么进行硬件重建呢？感谢

**Comment by giuliogamba** [comment]
Hi, the scripted hardware rebuilt flow in Windows is not supported, but you can analyze the scripts called by the `make-hw.sh` script and try to reproduce the flow yourself. For a better experience, I would suggest using a virtual machine with a Unix system.

**Comment by gexianwei1231** [comment]
Can I get hls project by make-hw.sh？thanks
