### ISSUE TITLE
Not able to run tiny-yolo-image-loop.ipynb

### ISSUE THREAD

**Issue by Nopileos2** [Xilinx/QNN-MO-PYNQ#8]
I was not able to run tiny-yolo-image-loop.ipynb out of the box, when trying to run the code in the box after "**2. Launch Demo**", I got this error

```
NameError                                 Traceback (most recent call last)`
<ipython-input-3-282cc81fa050> in <module>()
     59             print("class: {}\tprobability: {}".format(det[1], det[0]))
     60         res = Image.open(file_name_out.value.decode() + ".png")
---> 61         display(res)

NameError: name 'display' is not defined
```
I was able to fix this with adding the following line to the imports

`from IPython.display import display`

**Comment by giuliogamba** [comment]
Hi, 

which PYNQ image are you using?
You can discover the version with the instruction: `python3.6 -m pip show pynq`


 

>

**Comment by Nopileos2** [comment]
Hello sorry for the delayed response, this is the output of the command:

> Name: pynq
> Version: 1.4
> Summary: Python for Xilinx package
> Home-page: https://github.com/Xilinx/PYNQ
> Author: XilinxPythonProject
> Author-email: pynq_support@xilinx.com
> License: UNKNOWN
> Location: /opt/python3.6/lib/python3.6/site-packages
> Requires:

**Comment by giuliogamba** [comment]
Hi, 

so the problem is that you are using an old image. Please download the latest 2.1 image [here](http://files.digilent.com/Products/PYNQ/pynq_z1_v2.1.img.zip).
